change detection:
  provuuider: [".py", ".sh", ".js", ".ts", ".html", ".css"]

style:
  language:
    commit: "ko"             # "en" or "ko"
  style:
    commit_final: "internal_detail" # 템플릿명 (예: internal, solo_detail 등)

notify:
  platform: ["kakao", "discord", "gmail", "slack"]
  language: "ko"
record:
  platform: ["notion", "slack"]
  language: ["ko"]

timezone:
  commit: "Asia/Seoul" # "Asia/Seoul" or "UTC"
  record: "Asia/Seoul" # "Asia/Seoul" or "UTC"

debug mode: "on"